---

install:
  - choco install cyg-get
  - SET PATH=%PATH%;C:\Cygwin
  - cyg-get default
  - cyg-get perl
  - cyg-get make
  - cyg-get curl
  - cyg-get perl-libwww-perl
  - cyg-get perl-LWP-Protocol-https
  - cyg-get perl-Clone
  - cyg-get perl-ExtUtils-CBuilder
  - cyg-get perl-ExtUtils-MakeMaker
  - C:\Cygwin\bin\sh -lc "set -euo pipefail;
      IFS=$'\n\t';
      curl -L https://cpanmin.us | perl - -l~/perl5 App::cpanminus local::lib;
      perl -I/home/$USER/perl5/lib/perl5 -Mlocal::lib > ~/.bashrc"
  - C:\Cygwin\bin\sh -lc "set -euo pipefail;
      IFS=$'\n\t';
      cpanm -n Dist::Zilla;
      cd /cygdrive/c/projects/$APPVEYOR_PROJECT_NAME;
      dzil authordeps --missing | cpanm -n;
      dzil listdeps --missing | cpanm -n;
      cpanm -n Mojolicious"

build: off

test_script:
  - C:\Cygwin\bin\sh -lc "cd /cygdrive/c/projects/$APPVEYOR_PROJECT_NAME;dzil test -v"

cache:
  - C:\Cygwin\home

shallow_clone: true
