language: perl
sudo: false

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n
  - cpanm Mojolicious || true

script:
  - dzil test -v

perl:
  - "5.22"
  - "5.20"
  - "5.20-shrplib"
  - "5.18"
  - "5.18-shrplib"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
